package cuda.dsl.macros

import scala.annotation.{MacroAnnotation, experimental}
import scala.quoted.*
import cuda.dsl.core.Ptr

/** Macro for MPS (Metal Performance Shaders) GPU acceleration.
 *  Transforms Scala functions into PyTorch MPS operation chains at compile time.
 */
@experimental
class mpsKernel extends MacroAnnotation:
  def transform(using Quotes)(definition: quotes.reflect.Definition, companion: Option[quotes.reflect.Definition]): List[quotes.reflect.Definition] =
    import quotes.reflect.*
    definition match
      case DefDef(name, paramss, tpt, Some(rhs)) =>
        val opChain = generateMPSOps(rhs)
        val paramInfo = paramss.flatMap(_.params).collect {
          case ValDef(n, tpt, _) =>
            (n, typeToMPSString(tpt.tpe))
        }
        val paramDecls = paramInfo.map((n, t) => s"$t $n").mkString(", ")

        val mpsCode = s"""
// ============================================================================
// MPS Kernel: $name
// Generated by CUDA DSL @mpsKernel at compile time
// ============================================================================
def ${name}_mps_opchain(${paramDecls}): mps.OpChain = {
  mps.OpChain("${name}", Seq(
${opChain._1}
  ), ${opChain._2})
}
// ============================================================================
""".trim

        System.err.println(s"[@mpsKernel] Generated MPS Kernel: $name")
        System.err.println(mpsCode)

        // Write to file
        try
          val outputFile = new java.io.FileWriter("/tmp/cuda_dsl_generated_mps_kernels.txt", true)
          outputFile.write(s"[@mpsKernel] $name\n$mpsCode\n\n")
          outputFile.close()
        catch
          case e: Exception =>
            System.err.println(s"[@mpsKernel] Could not write to file: ${e.getMessage}")

        List(definition)
      case _ =>
        report.errorAndAbort("@mpsKernel can only be applied to functions")

/** Macro for MPS operators - generates fused operation chains */
@experimental
class mpsOperator extends MacroAnnotation:
  def transform(using Quotes)(definition: quotes.reflect.Definition, companion: Option[quotes.reflect.Definition]): List[quotes.reflect.Definition] =
    import quotes.reflect.*
    definition match
      case DefDef(name, paramss, tpt, Some(rhs)) =>
        val opChain = generateMPSOps(rhs)
        val paramNames = paramss.flatMap(_.params).collect { case ValDef(n, _, _) => n }.mkString(", ")

        val mpsCode = s"""
// [@mpsOperator] ${name}_op
def ${name}_mps_op(${paramNames}): mps.OpChain = {
  mps.OpChain("${name}_op", Seq(
${opChain._1}
  ), ${opChain._2})
}
""".trim

        System.err.println(s"[@mpsOperator] Generated MPS Operator: ${name}_op")
        System.err.println(mpsCode)

        List(definition)
      case _ =>
        report.errorAndAbort("@mpsOperator can only be applied to functions")

/** Generate MPS operations from Scala AST */
private def generateMPSOps(using Quotes)(expr: quotes.reflect.Term): (String, String) = {
  import quotes.reflect.*

  expr match
    case Apply(Select(lhs, "+"), List(rhs)) =>
      val (lCode, lInputs) = generateMPSOps(lhs)
      val (rCode, rInputs) = generateMPSOps(rhs)
      (s"    mps.Add($lCode, $rCode)", (lInputs :: rInputs :: Nil).distinct.mkString(", "))

    case Apply(Select(lhs, "-"), List(rhs)) =>
      val (lCode, lInputs) = generateMPSOps(lhs)
      val (rCode, rInputs) = generateMPSOps(rhs)
      (s"    mps.Sub($lCode, $rCode)", (lInputs :: rInputs :: Nil).distinct.mkString(", "))

    case Apply(Select(lhs, "*"), List(rhs)) =>
      val (lCode, lInputs) = generateMPSOps(lhs)
      val (rCode, rInputs) = generateMPSOps(rhs)
      (s"    mps.Mul($lCode, $rCode)", (lInputs :: rInputs :: Nil).distinct.mkString(", "))

    case Apply(Select(lhs, "/"), List(rhs)) =>
      val (lCode, lInputs) = generateMPSOps(lhs)
      val (rCode, rInputs) = generateMPSOps(rhs)
      (s"    mps.Div($lCode, $rCode)", (lInputs :: rInputs :: Nil).distinct.mkString(", "))

    case Apply(Select(lhs, ">"), List(rhs)) =>
      val (lCode, lInputs) = generateMPSOps(lhs)
      val (rCode, rInputs) = generateMPSOps(rhs)
      (s"    mps.Gt($lCode, $rCode)", (lInputs :: rInputs :: Nil).distinct.mkString(", "))

    case Apply(Select(lhs, "<"), List(rhs)) =>
      val (lCode, lInputs) = generateMPSOps(lhs)
      val (rCode, rInputs) = generateMPSOps(rhs)
      (s"    mps.Lt($lCode, $rCode)", (lInputs :: rInputs :: Nil).distinct.mkString(", "))

    case Apply(Select(lhs, ">="), List(rhs)) =>
      val (lCode, lInputs) = generateMPSOps(lhs)
      val (rCode, rInputs) = generateMPSOps(rhs)
      (s"    mps.Ge($lCode, $rCode)", (lInputs :: rInputs :: Nil).distinct.mkString(", "))

    case Apply(Select(lhs, "<="), List(rhs)) =>
      val (lCode, lInputs) = generateMPSOps(lhs)
      val (rCode, rInputs) = generateMPSOps(rhs)
      (s"    mps.Le($lCode, $rCode)", (lInputs :: rInputs :: Nil).distinct.mkString(", "))

    case Apply(Select(lhs, "=="), List(rhs)) =>
      val (lCode, lInputs) = generateMPSOps(lhs)
      val (rCode, rInputs) = generateMPSOps(rhs)
      (s"    mps.Eq($lCode, $rCode)", (lInputs :: rInputs :: Nil).distinct.mkString(", "))

    case Apply(Select(lhs, "!="), List(rhs)) =>
      val (lCode, lInputs) = generateMPSOps(lhs)
      val (rCode, rInputs) = generateMPSOps(rhs)
      (s"    mps.Ne($lCode, $rCode)", (lInputs :: rInputs :: Nil).distinct.mkString(", "))

    case Apply(Select(obj, "abs"), Nil) =>
      val (objCode, objInputs) = generateMPSOps(obj)
      (s"    mps.Abs($objCode)", objInputs)

    case Apply(Select(obj, "sqrt"), Nil) =>
      val (objCode, objInputs) = generateMPSOps(obj)
      (s"    mps.Sqrt($objCode)", objInputs)

    case Apply(Select(obj, "exp"), Nil) =>
      val (objCode, objInputs) = generateMPSOps(obj)
      (s"    mps.Exp($objCode)", objInputs)

    case Apply(Select(obj, "log"), Nil) =>
      val (objCode, objInputs) = generateMPSOps(obj)
      (s"    mps.Log($objCode)", objInputs)

    case Apply(Select(obj, "sin"), Nil) =>
      val (objCode, objInputs) = generateMPSOps(obj)
      (s"    mps.Sin($objCode)", objInputs)

    case Apply(Select(obj, "cos"), Nil) =>
      val (objCode, objInputs) = generateMPSOps(obj)
      (s"    mps.Cos($objCode)", objInputs)

    case Apply(Select(obj, "max"), List(arg)) if arg.symbol.fullName == "scala.math.package.NegativeInfinity" =>
      val (objCode, objInputs) = generateMPSOps(obj)
      (s"    mps.ReLU($objCode)", objInputs)

    case Apply(Select(obj, "apply"), List(idx)) =>
      val (objCode, objInputs) = generateMPSOps(obj)
      val (idxCode, idxInputs) = generateMPSOps(idx)
      (s"    mps.Index($objCode, $idxCode)", (objInputs :: idxInputs :: Nil).distinct.mkString(", "))

    case If(cond, thenp, elsep) =>
      val (condCode, condInputs) = generateMPSOps(cond)
      val (thenCode, thenInputs) = generateMPSOps(thenp)
      val (elseCode, elseInputs) = generateMPSOps(elsep)
      val inputs = (condInputs :: thenInputs :: elseInputs :: Nil).distinct.filter(_.nonEmpty).mkString(", ")
      (s"    mps.Where($condCode, $thenCode, $elseCode)", inputs)

    case Literal(IntConstant(i)) =>
      (s"    mps.Constant($i)", "")

    case Literal(FloatConstant(f)) =>
      (s"    mps.Constant($f)", "")

    case Literal(DoubleConstant(d)) =>
      (s"    mps.Constant(${d}f)", "")

    case Literal(LongConstant(l)) =>
      (s"    mps.Constant(${l}L)", "")

    case Literal(BooleanConstant(b)) =>
      (s"    mps.Constant($b)", "")

    case Literal(StringConstant(s)) =>
      (s"""    mps.Constant("$s")""", "")

    case Ident(name) if name != "nil" =>
      (s"    mps.Input(\"$name\")", name: String)

    case Select(obj, field) =>
      val (objCode, objInputs) = generateMPSOps(obj)
      (s"    mps.GetField($objCode, \"$field\")", objInputs)

    case Block(stats, lastExpr) =>
      val statOps = stats.collect { case s: Term => generateMPSOps(s) }
      val lastOps = generateMPSOps(lastExpr)
      val allInputs = (statOps.map(_._2) :+ lastOps._2).filter(_.nonEmpty).distinct.mkString(", ")
      (s"    // Block with ${stats.length} statements\n    mps.Identity(${lastOps._1})", allInputs)

    case _ =>
      (s"""    mps.Unsupported("${expr.show.replace("\"", "\\\"")}")""", "")
}

/** Convert Scala type to MPS parameter type string */
private def typeToMPSString(using Quotes)(tpe: quotes.reflect.TypeRepr): String = {
  import quotes.reflect.*

  tpe match
    case t if t =:= TypeRepr.of[Float] => "Float"
    case t if t =:= TypeRepr.of[Int] => "Int"
    case t if t =:= TypeRepr.of[Long] => "Long"
    case t if t =:= TypeRepr.of[Double] => "Double"
    case t if t =:= TypeRepr.of[Boolean] => "Boolean"
    case t if t <:< TypeRepr.of[Ptr[?]] => "Tensor"
    case t if t <:< TypeRepr.of[Array[?]] => "Tensor"
    case _ => "Tensor"
}
